# Link the Microsoft C runtime into the Windows programs, so Benchmark.exe and
# BenchmarkPassword.exe run on computers without the Visual C++
# Redistributable (no "VCRUNTIME140.dll was not found").
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
